Repository ssec/polar2grid, pull requests merged in 2019-08, with the labels that each got.

#194 Fix behave not being found
  integration_tests/run.sh
Labels: component:build

#195 Add --radius-of-influence flag for nearest neighbor resampling
  NEWS.rst
  NEWS_GEO2GRID.rst
  doc/source/introduction.rst
  polar2grid/glue.py
Labels: component:remap, enhancement

#199 Set default grid_coverage for VIIRS Active Fires to 0
  polar2grid/readers/viirs_edr_active_fires.py
  polar2grid/remap/remap.py
Labels: bug

#200 Fix VIIRS EDR Active Fires confidence_pct rescaling configuration
  polar2grid/core/rescale_configs/rescale.ini
Labels: bug

#198 Add ability to native resample to lower resolution grids
  NEWS_GEO2GRID.rst
  build_environment.yml
  doc/source/grids.rst
  doc/source/introduction.rst
  polar2grid/core/containers.py
  polar2grid/glue.py
  polar2grid/grids/grids.conf
Labels: bug

#206 Set default VIIRS EDR Active Fires products
  polar2grid/readers/mersi2_l1b.py
  polar2grid/readers/viirs_edr_active_fires.py
  polar2grid/readers/virr_l1b.py
Labels: bug, component:reader

#201 Fix rescaling configuration for some active fires variables
  polar2grid/core/rescale_configs/rescale.ini
  polar2grid/readers/__init__.py
Labels: bug

#208 Fix MERSI-2 L1B generation of true_color RGB
  build_environment.yml
  polar2grid/core/script_utils.py
  polar2grid/glue_legacy.py
  polar2grid/readers/__init__.py
Labels: bug, component:composite
