Repository ssec/polar2grid, pull requests merged in 2019-06, with the labels that each got.

#171 Add palettize rescaling option to colormap data in one step
  doc/source/rescaling.rst
  doc/source/utilscripts.rst
  polar2grid/add_colormap.py
  polar2grid/core/rescale.py
  polar2grid/core/rescale_configs/rescale.ini
  polar2grid/core/roles.py
  polar2grid/gtiff_backend.py
  polar2grid/readers/__init__.py
  setup.py
Labels: component:enhancement, enhancement

#173 Add '--borders-width' flag to add_coastlines.sh
  polar2grid/add_coastlines.py
Labels: component:utility, enhancement

#174 Fix readable permissions for bundled GSHHG shapefiles
  create_conda_software_bundle.sh
Labels: bug, component:build

#175 Add coastline, river, and grid width arguments to add_coastlines.sh
  polar2grid/add_coastlines.py
Labels: component:utility, enhancement

#177 Add conda build environment file and other fixes
  build_environment.yml
  create_conda_software_bundle.sh
  polar2grid/core/proj.py
  polar2grid/remap/_ll2cr.c
  polar2grid/remap/_ll2cr.pyx
  setup.py
  swbundle/polar2grid.sh
Labels: component:build, enhancement

#172 Add VIRR_l1b, MERSI2_l1b, VIIRS_edr_flood, and VIIRS_edr_active_fires readers
  doc/source/readers/mersi2_l1b.rst
  doc/source/readers/viirs_edr_active_fires.rst
  doc/source/readers/viirs_edr_flood.rst
  doc/source/readers/virr_l1b.rst
  polar2grid/modis/modis_to_swath.py
  polar2grid/readers/mersi2_l1b.py
  polar2grid/readers/viirs_edr_active_fires.py
  polar2grid/readers/viirs_edr_flood.py
  polar2grid/readers/virr_l1b.py
  setup.py
Labels: component:reader, enhancement

#178 Add a colormap for the WaterDetection product from the VIIRS EDR Flood reader
  polar2grid/core/proj.py
  polar2grid/core/rescale.py
  polar2grid/core/rescale_configs/rescale.ini
  polar2grid/readers/__init__.py
  polar2grid/readers/viirs_edr_flood.py
  polar2grid/remap/_ll2cr.c
  polar2grid/remap/_ll2cr.pyx
  swbundle/colormaps/viirs_edr_flood_water_detection.cmap
Labels: component:enhancement, enhancement

#179 Fix fill_value handling for integer type data
  polar2grid/core/containers.py
  polar2grid/core/rescale.py
  polar2grid/glue_legacy.py
  polar2grid/readers/__init__.py
  polar2grid/remap/remap.py
Labels: bug

#181 Fix ll2cr cols/rows not supporting 64-bit floats
  polar2grid/remap/remap.py
Labels: bug, component:remap
