Repository ssec/polar2grid, pull requests merged in 2020-09, with the labels that each got.

#260 Add new SCMI command line flags for tiled VIIRS EDR Flood support
  polar2grid/writers/scmi.py
Labels: component:writer, enhancement

#293 Remove old re_upload script for RealEarth
  Makefile
  README.rst
  create_conda_software_bundle.sh
Labels: component:build

#294 Add optional positional argument for passing files
  .travis.yml
  build_environment.yml
  create_conda_software_bundle.sh
  create_dev_env.sh
  create_software_bundle.sh
  polar2grid/add_colormap.py
  polar2grid/glue.py
  setup.py
  swbundle/add_coastlines.sh
  swbundle/add_colormap.sh
  swbundle/download_pyspectral_data.sh
  swbundle/env.sh
  swbundle/geo2grid.sh
  swbundle/gtiff2kmz.sh
  swbundle/gtiff2mp4.sh
  swbundle/hdf5_backend.sh
  swbundle/overlay.sh
  swbundle/polar2grid.sh
  swbundle/reproject_goes.sh
Labels: component:reader, enhancement

#295 Add support for Metop-C in MIRS reader
  polar2grid/mirs/mirs2swath.py
Labels: component:reader, enhancement
