Repository ssec/polar2grid, pull requests merged in 2021-04, with the labels that each got.

#333 Overhaul mapping of Satpy to Polar2Grid names
  .pre-commit-config.yaml
  etc/composites/viirs.yaml
  integration_tests/features/polar2grid_product_list.feature
  integration_tests/features/steps/compare_images.py
  polar2grid/glue.py
  polar2grid/readers/_base.py
  polar2grid/readers/mirs.py
  polar2grid/readers/viirs_sdr.py
  polar2grid/utils/dynamic_imports.py
  polar2grid/utils/legacy_compat.py
  polar2grid/writers/awips_tiled.py
  polar2grid/writers/geotiff.py
  pyproject.toml
Labels: component:reader, component:writer, enhancement

#334 Fix geo2grid readers with new ReaderProxy classes
  integration_tests/features/geo2grid.feature
  integration_tests/features/polar2grid.feature
  integration_tests/features/polar2grid_product_list.feature
  integration_tests/features/steps/compare_images.py
  polar2grid/readers/_base.py
  polar2grid/readers/abi_l1b.py
  polar2grid/readers/ahi_hrit.py
  polar2grid/readers/ahi_hsd.py
  polar2grid/utils/legacy_compat.py
Labels: component:reader

#337 Fix rows_per_scan not being defined for MiRS resampling
  etc/resampling.yaml
Labels: bug, component:remap

#335 Add satpy-compatible flat binary file writer
  MANIFEST.in
  build_environment.yml
  create_conda_software_bundle.sh
  etc/writers/binary.yaml
  polar2grid/core/dtype.py
  polar2grid/core/script_utils.py
  polar2grid/glue.py
  polar2grid/tests/__init__.py
  polar2grid/tests/etc/enhancements/generic.yaml
  polar2grid/tests/test_writers/__init__.py
  polar2grid/tests/test_writers/test_binary.py
  polar2grid/writers/binary.py
  polar2grid/writers/geotiff.py
Labels: component:writer, enhancement

#338 Fix description of --radius-of-influence units
  polar2grid/glue.py
Labels: component:remap, documentation

#339 Add new MiRS integration tests
  integration_tests/features/polar2grid.feature
  integration_tests/features/steps/compare_images.py
  polar2grid/compare.py
  swbundle/p2g_compare.sh
Labels: component:build

#341 Fix inconsistent noaa20 platform naming for various readers
  polar2grid/glue.py
Labels: bug, component:reader, component:utility

#343 Add initial draft of adding new readers documentation
  .gitignore
  NEWS.rst
  continuous_integration/environment.yaml
  doc/source/conf.py
  doc/source/design_overview.rst
  doc/source/dev_guide/adding_readers.rst
  doc/source/dev_guide/api/.gitkeep
  doc/source/dev_guide/dev_env.rst
  doc/source/dev_guide/index.rst
  doc/source/dev_guide/json_input.rst
  doc/source/dev_guide/swbundle.rst
  doc/source/index.rst
  doc/source/introduction.rst
  doc/source/overview.rst
  doc/source/rescaling.rst
  jenkins_environment.yml
  polar2grid/avhrr/readers.py
  setup.py
Labels: documentation

#342 Change binary writer to default 64-bit floats to 32-bit floats
  doc/source/readers/viirs_sdr.rst
  etc/enhancements/abi.yaml
  etc/enhancements/ahi.yaml
  etc/enhancements/generic.yaml
  etc/enhancements/viirs.yaml
  integration_tests/features/steps/compare_images.py
  polar2grid/compare.py
  polar2grid/resample/_resample_scene.py
  polar2grid/tests/test_writers/test_binary.py
  polar2grid/writers/binary.py
  polar2grid/writers/geotiff.py
Labels: component:writer, enhancement

#340 Add ability for compare script to compare all NC/HDF5 variables
  polar2grid/compare.py
Labels: component:utility, enhancement

#321 Add Satpy-compatible 'hdf5' writer
  etc/writers/hdf5.yaml
  polar2grid/glue.py
  polar2grid/utils/legacy_compat.py
  polar2grid/writers/hdf5.py
Labels: component:writer, enhancement

#346 Overhaul comparison scripts to provide summary HTML pages
  integration_tests/features/environment.py
  integration_tests/features/steps/compare_images.py
  integration_tests/run.sh
  polar2grid/compare.py
  swbundle/p2g_compare.sh
  swbundle/p2g_compare_geotiff.sh
  swbundle/p2g_compare_netcdf.sh
Labels: component:build, enhancement
