Repository ssec/polar2grid, pull requests merged in 2022-04, with the labels that each got.

#443 Fix --dnb-saturation-correction flag clearing default product list
  polar2grid/enhancements/shared.py
  polar2grid/readers/viirs_sdr.py
  polar2grid/tests/conftest.py
  polar2grid/tests/test_enhancements.py
  polar2grid/tests/test_glue.py
  polar2grid/tests/test_resample/test_resample_scene.py
  polar2grid/tests/test_writers/test_hdf5.py
Labels: bug, component:reader, component:enhancement

#445 Fix resampling kwargs not being passed in some situations
  etc/resampling.yaml
  polar2grid/resample/_resample_scene.py
  polar2grid/resample/resample_decisions.py
  polar2grid/tests/test_resample/test_resample_scene.py
  swbundle/convert_grids_conf_to_yaml.sh
  swbundle/env.sh
Labels: bug, component:remap

#446 Fix add_colormap.sh not interpolating partial colormaps
  .pre-commit-config.yaml
  polar2grid/add_colormap.py
  polar2grid/readers/viirs_sdr.py
  polar2grid/tests/etc/colormaps/WV_Chile_Short.cmap
  polar2grid/tests/test_add_colormap.py
  polar2grid/tests/test_glue.py
Labels: bug, component:utility

#447 Refactor main glue script for better code complexity
  doc/source/getting_started.rst
  doc/source/installation.rst
  doc/source/remapping.rst
  polar2grid/_glue_argparser.py
  polar2grid/glue.py
  polar2grid/tests/test_glue.py
Labels: code cleanup

#448 Refactor compare.py script for cleaner code
  polar2grid/compare.py
Labels: code cleanup

#450 Move existing colormaps to etc directory
  create_conda_software_bundle.sh
  etc/colormaps/amsr2_36h.cmap
  etc/colormaps/amsr2_89h.cmap
  etc/colormaps/hsl256_no_black.cmap
  etc/colormaps/p2g_sst_palette.txt
  etc/colormaps/tropix_no_white.cmap
  etc/colormaps/viirs_edr_flood_water_detection.cmap
  polar2grid/tests/etc/enhancements/generic.yaml
Labels: component:build

#451 Fix missing example_enhancements directory in software bundle
  create_conda_software_bundle.sh
  etc/composites/modis.yaml
Labels: bug, component:build

#435 Add command line option to mask saturated modis_l1b band 2 pixels
  etc/enhancements/modis.yaml
  polar2grid/readers/modis_l1b.py
Labels: bug, component:reader

#452 Fix AVHRR reader using "avhrr-3" name instead of "avhrr"
  doc/source/readers/avhrr.rst
  integration_tests/features/polar2grid.feature
  polar2grid/_glue_argparser.py
  polar2grid/glue.py
  polar2grid/writers/geotiff.py
Labels: bug, component:reader

#453 Fix legacy dynamic grids not working with negative resolutions
  polar2grid/core/containers.py
  polar2grid/tests/test_grids/test_manager.py
Labels: bug, component:remap

#459 Fix bundle initialization to use embedded openssl
  swbundle/env.sh
Labels: component:build

#460 Fix bundle creation not creating geo2grid properly
  create_conda_software_bundle.sh
  swbundle/GEO2GRID_README.txt
  swbundle/POLAR2GRID_README.txt
Labels: bug, component:build

#462 Add CodeScene badge to README
  README.rst
Labels: documentation

#463 Cleanup add_coastlines.py
  polar2grid/add_coastlines.py
Labels: code cleanup

#464 Add thumbnail generation for more formats in compare script
  .pre-commit-config.yaml
  polar2grid/compare.py
  polar2grid/tests/test_compare.py
Labels: enhancement, component:utility

#465 Fix compare script not producing images for x/y NetCDF variables
  polar2grid/compare.py
  polar2grid/tests/test_compare.py
Labels: bug, component:utility

#467 Remove legacy plot_ncdata.py utility script
  polar2grid/debug_data.py
  polar2grid/plot_ncdata.py
  swbundle/plot_ncdata.sh
Labels: code cleanup
