Repository ssec/polar2grid, pull requests merged in 2022-06, with the labels that each got.

#472 Add optimization to persist swath definition lon/lat arrays
  doc/source/custom_grids.rst
  polar2grid/_glue_argparser.py
  polar2grid/glue.py
Labels: optimization

#479 Fix grid coverage being performed on native resampling
  .github/workflows/ci.yaml
  polar2grid/_glue_argparser.py
  polar2grid/resample/_resample_scene.py
  polar2grid/tests/test_resample/test_resample_scene.py
Labels: bug, component:remap

#481 Fix overlay.sh script not preserving compression and tiling
  swbundle/overlay.sh
Labels: bug, component:utility

#482 Add --no-mask-space flag to AHI HSD reader
  polar2grid/readers/ahi_hsd.py
Labels: enhancement, component:reader

#483 Fix persisting geolocations not actually persisting
  polar2grid/filters/day_night.py
  polar2grid/glue.py
  polar2grid/resample/_resample_scene.py
  polar2grid/tests/conftest.py
  polar2grid/tests/test_glue.py
  polar2grid/tests/test_resample/test_resample_scene.py
Labels: bug

#476 Add CF-complaint NetCDF writer (cf)
  polar2grid/writers/cf.py
Labels: enhancement, component:writer
