Repository ssec/polar2grid, pull requests merged in 2023-02, with the labels that each got.

#590 Fix integration tests not being specific enough when listing products
  integration_tests/features/steps/compare_images.py
Labels: bug, component:build, code cleanup

#592 Update expected test values for boundaries of geostationary data
  polar2grid/tests/test_filters/test_utils.py
Labels: code cleanup

#593 Fix MODIS AWIPS configuration using wrong product names
  etc/writers/awips_tiled.yaml
  polar2grid/readers/modis_l1b.py
Labels: bug, component:writer

#595 Fix missing units for dynamic DNB saturation in AWIPS config
  build_environment.yml
  etc/writers/awips_tiled.yaml
  polar2grid/writers/hdf5.py
Labels: bug, component:writer

#598 Final documentation updates for P2G 3.0 release
  NEWS.rst
  doc/source/conf.py
  doc/source/examples/amsr2_example.rst
  doc/source/examples/modis_example.rst
  doc/source/index.rst
  doc/source/introduction.rst
  doc/source/readers/acspo.rst
  doc/source/readers/mirs.rst
  doc/source/version3_implementation.rst
  polar2grid/readers/ami_l1b.py
Labels: documentation

#599 Final minor cleanup of the P2G Version 3.0 What's New section.
  NEWS.rst
Labels: documentation

#596 Fix colormaps being converted to rasterio colortables
  polar2grid/add_colormap.py
  polar2grid/tests/etc/colormaps/reds.cmap
  polar2grid/tests/test_add_colormap.py
Labels: bug, component:utility

#597 Fix gtiff2mp4.sh to workaround ffmpeg tiled gtiff issues
  swbundle/gtiff2mp4.sh
Labels: bug, component:utility
